### ISSUE TITLE
#import <Pusher/Pusher.h> not found

### ISSUE THREAD

**Issue by jqn** [b8ne/react-native-pusher-push-notifications#1]
Hi, first of all I would like to thank you for your hard work. I was wondering if you could help with this problem I keep having while trying to use this package. Xcode shows a `#import <Pusher/Pusher.h> not found` and I have the libPusher library installed with CocoaPods.

**Comment by b8ne** [comment]
Hey @jqn thanks mate. Just put this module up to get used to npm, didnt realise people would start downloading it straight away.
Try going to the `RNPusherPushNotification` library in Xcode.
Then add `$(SRCROOT)/../../../ios/Pods/Headers/Public/libPusher` to Header Search Paths.
Let me know how you go, if it works ill add it to the readme.
Or let me know if there is a better way :)

**Comment by jqn** [comment]
Hi @b8ne this package just happens to resolve one issue I'm currently facing in my app. I realize this is extremely new and thanks for helping out. It would be great to see this component grow. Adding the header search path worked but now I'm facing a new error:

` +(void)setPusher:(PtPusher *)pusher` is throwing a `Thread 1: EXC_BAD_ACCESS(code=2, address-0x16fca7fd0)`

I don't really know objective-c but it seems that this could be causing an infinite loop `self.pusher = pusher`

**Comment by b8ne** [comment]
Hey @jqn yeah i was getting the same yesterday. I pushed a patch, i think its v0.1.7 so try that.
Not sure why but moving the init to a different method helped - so the updated readme.
Yeah objective c is all new to me too. I initially had this module hard coded in the main project, so its been a challenge moving it to a library.

**Comment by jqn** [comment]
Hmmm.... not seeing version 0.17

**Comment by b8ne** [comment]
Should be 0.1.7 or just checkout the updated README.
Yeah mate PRs are welcome, go for it.

**Comment by jqn** [comment]
Ok 0.17 keeps throwing the same error. I'll keep looking into it a see if I can help figure out why it keeps throwing the infinite loop.

**Comment by cameronkloot** [comment]
Hey @jqn, did you figure out the loop issue?

**Comment by jqn** [comment]
I didn't, I ended up using the pusher client api to subscribe and libpusher for iOS and pusher websocket android for android

https://pusher.com/docs/push_notifications/reference/client_api

**Comment by pesakitan22** [comment]
@jqn hello, how do you integrate native libraries into react-native? 

thanks

**Comment by jqn** [comment]
@pesakitan22 if you are referring to the pusher native library this is a nice guide on how to do it for iOS

**Comment by b8ne** [comment]
Thanks @jqn sorry ive been off RN projects for a while so havent had much time to work on this.  I can see you've used a workaround, however one of my colleagues has used this package successfully so I'll mark this as closed for now.
@pesakitan22 do you mean libraries like this one in general? The README for this project is based off a template and I believe its a pretty nice walkthrough to get everything setup.
If you are referring to the pusher library, [these docs](https://pusher.com/docs/push_notifications) are very comprehensive.

**Comment by pesakitan22** [comment]
@b8ne thanks for this package, but it's still throwing infinite loop, on  `+(void)setPusher:(PtPusher *)pusher`

**Comment by se1exin** [comment]
@pesakitan22 @jqn Fixes for iOS are now in the `dev` branch.

`npm install --save git+https://github.com/b8ne/react-native#dev`

If your able to, it would be awesome if you could test it out and report if it fixes the issues?

Note the setup instructions and different on this branch due to significant changes in the iOS implementation - most notably the changes to `AppDelegate.h` and `AppDelegate.m`. Just shout out on here if you need a hand getting it setup.

**Comment by pesakitan22** [comment]
i have a similar implementation like your codes on live app.
gonna try yours later @se1exin 

thanks

**Comment by jqn** [comment]
@pesakitan22 - thanks, I'll test it out

**Comment by se1exin** [comment]
@pesakitan22 @jqn FYI version 1.0.0 has been released and is now available on npm. Both Android and iOS have been extensively tested and is currently in use in a production app, so consider this good to go.

**Comment by ahmed-wagdi** [comment]
@se1exin i updated to version 1.0.1 but when i add the line:
`#import "RNPusherPushNotifications.h"`
 i'm getting the error `"RNPusherPushNotifications.h" file not found`

**Comment by se1exin** [comment]
Hi @ahmed-wagdi sounds like a linking issue. Did your run `react-native link react-native-pusher-push-notifications`?

In Xcode under your Libraries you should have `RNPusherPushNotifications.xcodeproj`

![libs](https://user-images.githubusercontent.com/2385350/28067837-4ec572c6-6686-11e7-98eb-a90b62f3957f.png)

----

In `General > Linked Frameworks and Libraries` you should have `libRNPusherPushNotifications.a (required)`

![link](https://user-images.githubusercontent.com/2385350/28067887-76f275f0-6686-11e7-88af-6e9ab84f4faa.png)

----

And under `Build Phases > Link Binaries With Libraries` you should have `libRNPusherPushNotifications.a (required)`

![build-phases](https://user-images.githubusercontent.com/2385350/28067926-a8fe98ee-6686-11e7-9117-5cf53163b1cd.png)

---

Do you have these in your project?

Also what version of React Native are you using?

**Comment by ahmed-wagdi** [comment]
@se1exin that solved my problem thanks!
