### ISSUE TITLE
[Proposal] Change RCTBridgeModule.h import syntax

### ISSUE THREAD

**Issue by augustoabreu** [b8ne/react-native-pusher-push-notifications#10]
Hi! First of all, I don't know so much about Objective-C.

Every time that i run `yarn` i have to change the RCTBridgeModule.h import syntax. I don't know why but `#import "RCTBridgeModule.h"` don't work for me.

The library only works with this syntax:
`#import <React/RCTBridgeModule.h>`

Can anyone explain why?

**Comment by se1exin** [comment]
Hi @augustoabreu Ahh that is the new syntax for React Native Obj-C imports - I can't remember which version number but it's from quite a few ago. Please use the `<>` syntax as you have mentioned, and I'll update the docs
