### ISSUE TITLE
not showing device in pusher beams dashboard when setInstanceId

### ISSUE THREAD

**Issue by partTimeCoder96** [b8ne/react-native-pusher-push-notifications#106]
export const PusherInstanceConnect = async () => {
                                                      try {
                                                        RNPusherPushNotifications.setInstanceId(
                                                          '',
                                                        );
                                                        RNPusherPushNotifications.on('notification', handleNotification);
                                                        RNPusherPushNotifications.setOnSubscriptionsChangedListener(
                                                          onSubscriptionsChanged,
                                                        );
                                                      } catch (error) {
                                                        console.log(error);
                                                      }
                                                    };

did I miss any step, follow all steps from the doc.

**Comment by JeanHules** [comment]
Did you figure this out? I have tried several different methods and nothing seems to register the interest.

**Comment by partTimeCoder96** [comment]
yes its working for both platform...i have do manual installation for both platform and its worked.

**Comment by Lakshyakatarmal** [comment]
@thtRajasthaniGuy  can you please share the steps for manual installation for both platforms?
