### ISSUE TITLE
No callback after subscribed or unsubscribed

### ISSUE THREAD

**Issue by thienlhh** [b8ne/react-native-pusher-push-notifications#13]
First thing I want thank you for creating this package and to day I want to use it for my project.

I'm using react native 0.46.1 and install this package, following this guide with proper information: pusher app id, channel. After run the application I don't see any callback of subscribe function, no error, no success.

What should I do? Thanks

**Comment by rishii95** [comment]
Same is the case with me..Please let us know if there is any solution to it.

**Comment by sksahil030** [comment]
Facing Same issue

**Comment by b8ne** [comment]
Hey @thienlhh @rishii95 @sksahil030 Looks like we implemented the callback in `RNPusherPushNotifications.java` but haven't invoked it in `PusherWrapper.java`
Ill im to patch this and merge this coming weekend.

**Comment by b8ne** [comment]
Hey @thienlhh @rishii95 @sksahil030 just merged #19 so closing for now, run an `npm update` and let me know if the problem persists.
