### ISSUE TITLE
Clarification on setAppKey()

### ISSUE THREAD

**Issue by realripley00** [b8ne/react-native-pusher-push-notifications#15]
I'm working through this and I'm not getting any kind of error, but whenever I push a test notification to the test interest, I'm not getting a push notification.

I was wondering about this line:
RNPusherPushNotifications.setAppKey()
I've got this set to my Secret Key from dash.pusher.com.  Is that the key that should go there? Is there some other 'key' that I'm missing?  Any direction would be appreciated.

**Comment by b8ne** [comment]
Hey @realripley00 it should be your App Key.  Can you try that and see how it goes?

**Comment by b8ne** [comment]
Closing for now, let me know if there are any further issues

**Comment by ghulamHaiderbuggy** [comment]
![Uploading Screenshot_20210521-165810.png…]()

**Comment by ghulamHaiderbuggy** [comment]
![Screenshot_20210521-165810](https://user-images.githubusercontent.com/71820782/119135566-080ead00-ba58-11eb-85ed-72ec1b24c9d4.png)

**Comment by mahesh-syscon** [comment]
> are we set pusher app key? ![Screenshot_20210521-165810](https://user-images.githubusercontent.com/71820782/119135566-080ead00-ba58-11eb-85ed-72ec1b24c9d4.png)

i got same screen now. any solution to this issue??

**Comment by Lakshyakatarmal** [comment]
I am getting the same error on Android. any update?
