### ISSUE TITLE
How to add a FCMPushNotificationReceivedListener ?

### ISSUE THREAD

**Issue by LeoIannacone** [b8ne/react-native-pusher-push-notifications#17]
Hi,

how can I add a FCMPushNotificationReceivedListener ?

**Comment by b8ne** [comment]
Hey @LeoIannacone looks like this has been implemented in [PR #11  ](https://github.com/b8ne/react-native-pusher-push-notifications/pull/11)
Im hoping to review and merge that this weekend.

**Comment by b8ne** [comment]
@LeoIannacone just merged #19 so closing for now, let me know if there are any dramas
