### ISSUE TITLE
No visible interface PTPusher

### ISSUE THREAD

**Issue by jhumphrey1** [b8ne/react-native-pusher-push-notifications#22]
The lines inside RNPusherPushNotifications.m including:
[[[self pusher] nativePusher] subscribe:(NSString *)interest];
[[[self pusher] nativePusher] unsubscribe:(NSString *)interest];
[[[self pusher] nativePusher] registerWithDeviceToken:deviceToken];

are all throwing error 'No visible @interface for 'PTPusher' declares the selector 'nativePusher'

**Comment by b8ne** [comment]
Hey @jhumphrey1 version 2.0.0 has just been release to support Pusher Beams.  The install is a fair bit different, can you try upgrading and follow the install instructions again?
Given this is for the older version ill close this issue for now, let me know if you are still having issues.
