### ISSUE TITLE
Unable to build with 1.3.0 or 2.0.0 - ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is enabled, but the product type 'Static Library' is not a wrapper type.

### ISSUE THREAD

**Issue by dseipp** [b8ne/react-native-pusher-push-notifications#26]
I'm receiving the following warning when attempting to build with 1.3.0 or 2.0.0:

`ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is enabled, but the product type 'Static Library' is not a wrapper type.`

I'm able to build successfully with 1.2.2 but unfortunately that doesn't support Beams.

**Comment by dseipp** [comment]
Doing more digging into the reason for the build failure and will open a new issue at that time.

**Comment by janvdt** [comment]
Any update on this matter? I have the same problem

**Comment by dmitrizagidulin** [comment]
Likewise, ran into the same thing (following latest instructions).
