### ISSUE TITLE
Error callback is not fired on unsuccessful unsubscribe

### ISSUE THREAD

**Issue by ewal** [b8ne/react-native-pusher-push-notifications#29]
Hi, I implemented the `unsubscribe` method according to the example and sent in an incorrect interest name but the callbacks never fired. I did so by mistake I should add and was stuck with this for a while 😄 

```js
  RNPusherPushNotifications.unsubscribe('faulty-interest-name', (statusCode, response) => {
    console.tron.log(statusCode, response); // Nothing here
  }, () => {
    console.tron.log('Success'); // ... or here
  });

```
I'm using Reactotron for logging.

**Comment by b8ne** [comment]
Hi @ewal unfortunately only RN Android supports callbacks(that are stable) at the moment.  This will be implemented when we add support for Android.  I will also look to update our README to make this clearer.
