### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by ahmed-wagdi** [b8ne/react-native-pusher-push-notifications#3]
I followed the installation guide and added `$(SRCROOT)/../../../ios/Pods/Headers/Public/libPusher` to header search paths but the build is failing. I attached a screenshot of the xcode error:
<img width="1440" alt="screen shot 2017-06-19 at 3 58 28 pm" src="https://user-images.githubusercontent.com/8686483/27288809-3c2414cc-5508-11e7-9d30-9ea8a41c70d8.png">

**Comment by se1exin** [comment]
@ahmed-wagdi have you set the search path to `recursive`?

This is what my header paths looks like

![screen shot 2017-06-30 at 4 03 43 pm](https://user-images.githubusercontent.com/2385350/27722962-e5d38d7e-5dad-11e7-92b5-0235ec199bc6.png)
