### ISSUE TITLE
Module PushNotifications not found

### ISSUE THREAD

**Issue by kulkarniankita** [b8ne/react-native-pusher-push-notifications#31]
I have a React Native project created using `react-native init`. I followed the instructions to install the module but keep getting the following: @b8ne @emilkarl 

![screen shot 2018-08-30 at 2 44 07 pm](https://user-images.githubusercontent.com/2559673/44872324-307c6a80-ac63-11e8-9ea6-69261d5ea6b4.png)

Here are the steps:
`yarn add react-native-push-notification`
`react-native link react-native-push-notification`

Linking libraries:
![screen shot 2018-08-30 at 2 45 49 pm](https://user-images.githubusercontent.com/2559673/44872453-92d56b00-ac63-11e8-99be-f8d00f168680.png)
![screen shot 2018-08-30 at 2 46 01 pm](https://user-images.githubusercontent.com/2559673/44872461-979a1f00-ac63-11e8-8d43-32e335802f74.png)

Header search paths:
![screen shot 2018-08-30 at 2 46 17 pm](https://user-images.githubusercontent.com/2559673/44872470-9e289680-ac63-11e8-8f76-ef1e0df69d91.png)

I also tried re-installing all node modules but still no luck.
What am I missing here?

**Comment by emilkarl** [comment]
Did you install the Pusher Push Notifications library explained in the first part of the readme? Seems like you are missing that in your project.

https://github.com/b8ne/react-native-pusher-push-notifications#react-native-pusher-push-notifications

>This module is intended to complement the setup with Carthage. This module allows that implementation to be accessed directly from React Native JS.

>More information about Pusher Beams and their Swift library, push-notifications-swift, can be found on their Github repo.

>There are some issues installing this repo you need to be aware of. More info can be found in issue 65.

**Comment by kulkarniankita** [comment]
@alfonsosn I did get it to work by doing a carthage install
