### ISSUE TITLE
Recommended methods to interact with badge counts

### ISSUE THREAD

**Issue by gprocell927** [b8ne/react-native-pusher-push-notifications#36]
Is there currently a way to interact with badge counts using `RNPusherPushNotifications`? 
I'm currently seeking a way to clear the count upon entering the app from an icon press. In iOS, this seems to be handled simply via that AppDelegate.m file, but in Android, it seems to be more involved and that I would need to interfere with channels that might be set up via this library.

**Comment by Humni** [comment]
See the docs: https://github.com/b8ne/react-native-pusher-push-notifications#increment-badge-number

**Comment by anniewey** [comment]
@Humni how to clear notification badge when app is opened without dependency from backend?

**Comment by baraa-rasheed** [comment]
@anniewey There is a [ Pull request](https://github.com/b8ne/react-native-pusher-push-notifications/pull/92) regarding this but it's not merged yet.

for now you can use this patch, then you can clear the notification badge like below

`RNPusherPushNotifications.setApplicationIconBadgeNumber(0);`


[react-native-pusher-push-notifications+2.6.0.patch](https://github.com/user-attachments/files/21441039/react-native-pusher-push-notifications%2B2.6.0.patch)
