### ISSUE TITLE
Issues with RN 0.59, cannot find header declartions

### ISSUE THREAD

**Issue by emilkarl** [b8ne/react-native-pusher-push-notifications#37]
Im seeing these errors when trying to compile my project. Anyone seen these and solved it?

```
No visible @interface for 'PushNotifications' declares the selector 'unsubscribeWithInterest:error:completion:'
```

![image](https://user-images.githubusercontent.com/10711/56583330-9f834680-65d9-11e9-8bb4-d34a4c8c3d81.png)

**Comment by emilkarl** [comment]
Seems to be when using newer version of https://github.com/pusher/push-notifications-swift

https://github.com/pusher/push-notifications-swift/commit/c827c4654cc7ecad331dbf52d08d1e0effdbc7df

**Comment by NotTooReact89** [comment]
Hi I am still seeing this error in the new version of push-notifications-swift. Tried to downgrade it to 2.0.0 and I still see this.

**Comment by alanpilloud** [comment]
I am also experiencing this issue and tried to downgrade using version 2.0.0 too, without any chance.

@emilkarl Could you explain us how you got rid of these errors ?

**Comment by emilkarl** [comment]
@alanpilloud I fixed it by using the thing described in #38, specify an older version in the cartfile. 

`github "pusher/push-notifications-swift" ~> 2.0.0`

**Comment by emilkarl** [comment]
Are you sure you have downgraded to the correct version? This was a really long time ago so I cant really remember, all I know is that #38 solved it for me.

**Comment by alanpilloud** [comment]
@emilkarl This is what I tried first but using `~>` downloads the 2.1.2 version, so I also tried with `==` to get the exact version.

For react-native-pusher-push-notifications, I use version 2.1.0, so your Pull Request should be included in this version. However, I can't see your modifications in `RNPusherPushNotifications.m`.

I tried to search for the modifications you did in your PR, but they are not applied in the current version of react-native-pusher-push-notifications (2.1.0) and previous ones.

So I copy/pasted your code in my local RNPusherPushNotifications.m file and it worked. I will probably fork this project.

Now, I am wondering if this is an issue for everybody, or just those using react-native 0.59 ...

Anyway, thanks a lot for your help, this is very kind of you !

**Comment by emilkarl** [comment]
Hmm hard to say, have you tried? `github "pusher/push-notifications-swift" == 1.3.0` Unsure but I dont think 2.1 works.

**Comment by emilkarl** [comment]
@alanpilloud Had a look in my project now. 

```
"react-native-pusher-push-notifications": "^2.1.0",
```

**Comment by alanpilloud** [comment]
@emilkarl Thank you, I will try monday.

**Comment by alanpilloud** [comment]
@emilkarl Thanks a lot, this is working fine ! I've just had to go through the manual installation once again, and it's done.

Thanks again !
