### ISSUE TITLE
Notification callback not triggered on Android?

### ISSUE THREAD

**Issue by emilkarl** [b8ne/react-native-pusher-push-notifications#40]
I can't see any callbacks being triggered when opening the app by clicking the notification. The callbacks is called when the app is opened or in background. 

Have you looked in to this @mikebridge @b8ne ?

**Comment by emilkarl** [comment]
I made a PR for supporting deep links in `push-notifications-android`. If we can get that merged we could update this lib to use that version and include a little pitch about deep linking in the readme.

https://github.com/pusher/push-notifications-android/pull/76

**Comment by emilkarl** [comment]
I think using deep links would be a nicer way of handling opening the app from a notification than routing in a callback so if anyone want to help I would appreciate it. :)

**Comment by mikebridge** [comment]
I had hoped to look at this yesterday but it probably won't be until next week.  I'm not sure what you mean by the callbacks not being triggered when opening the app.

**Comment by Ahmdrza** [comment]
@emilkarl Hi, any updates on this issue?

**Comment by Humni** [comment]
Given the lack of update, I'll close this for now - if it is still an issue let me know
