### ISSUE TITLE
Errors building iOS with React Native 0.60.x

### ISSUE THREAD

**Issue by stephenkiers** [b8ne/react-native-pusher-push-notifications#46]
So our company has used RNPusherPushNotifications for over a year in our RN app. This last week I started the upgrade to [RN 0.60.x](https://facebook.github.io/react-native/blog/2019/07/03/version-60) but I have been blocked by this package for the last couple days. Would really appreciate help.

So here are relevant portions of our app,

**package.json**
```
...
"dependencies": {
"react-native-pusher-push-notifications": "git+http://git@github.com/ZeptInc/react-native-pusher-push-notifications#v.2.4.1-zept-master",
}
...
```

**react-native.config.js**
```
module.exports = {
    dependencies: {
        "react-native-pusher-push-notifications": {
            platforms: {
                android: null,
                ios: null
            }
        }
    }
};
```

**ios/Cartfile**
```
github "pusher/push-notifications-swift" ~> 2.0.0
```

And I have added `RNPusherPushNotifications.xcodeproj` to our app's library and linked the binary to the library 
<img width="1188" alt="Screenshot 2019-08-16 14 51 46" src="https://user-images.githubusercontent.com/1245512/63197617-87767d80-c035-11e9-823f-678ab3f627af.png">

But, when I try to build...
**22 Errors break the builds**
![Aug-16-2019 14-56-18-2](https://user-images.githubusercontent.com/1245512/63197804-08ce1000-c036-11e9-823b-dc11a140b683.gif)

So, I thought I would try changing the `Header Search Paths` in the `RNPusherPushNotifications.xcodeproj`project to see if they were the cause of the issue (based on StackOverflow hints) 

![Aug-16-2019 14-58-20](https://user-images.githubusercontent.com/1245512/63198150-11731600-c037-11e9-8f18-f9aaf872da2e.gif)

**1 Error breaks the build**
<img width="997" alt="Screenshot 2019-08-16 15 02 22" src="https://user-images.githubusercontent.com/1245512/63198161-16d06080-c037-11e9-8520-ddf6bb1ce016.png">
<img width="1025" alt="Screenshot 2019-08-16 15 02 40" src="https://user-images.githubusercontent.com/1245512/63198159-1637ca00-c037-11e9-93ae-af75fb8928ce.png">

### Send HELP!?!

but I honestly don't know if that is a step forward or a step back. 

Anyone else do this? Anyone have success yet? Any help that could be given is appreciated.

**Comment by stephenkiers** [comment]
Here are minimum repos for the issue : 
https://github.com/stephenkiers/PusherPushNotificationsSampleRepo/tree/CocoaPods
https://github.com/stephenkiers/PusherPushNotificationsSampleRepo/tree/Carthage

**Comment by lsirdevan** [comment]
@stephenkiers Thanks! Works great 

@b8ne Could we get #47 merged? It fixes this issue

**Comment by ErlanBelekov** [comment]
@stephenkiers hey! did you resolve this? if yes, please tell how, I need this package to work so bad! Thanks

**Comment by stephenkiers** [comment]
yeah, you can check out this branch https://github.com/b8ne/react-native-pusher-push-notifications/pull/48 for the current working version we use internally.
