### ISSUE TITLE
Handling opening app from push notification

### ISSUE THREAD

**Issue by mtflud** [b8ne/react-native-pusher-push-notifications#5]
Hi! Is there any way to handle a user opening the application from a push notification?

**Comment by se1exin** [comment]
Hi @mtflud - good question! At the moment the the app will simply open when a user taps the notification, however adding callbacks/events on the React Native side is next on the roadmap so keep an eye out in the next release.

As always, pull requests are more than welcome if you happen to give this a go yourself!

**Comment by alexbowers** [comment]
Any update on this?

**Comment by emilkarl** [comment]
I think this is fixed but there are still some issues in the current implementation. I'm currently investigating and working on a fix for it.

**Comment by emilkarl** [comment]
Think i solved it in #28. You have to handle it in the `inactive` state.
