### ISSUE TITLE
Support extra data for push notifications

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [b8ne/react-native-pusher-push-notifications#52]
At the moment this library is ignoring the extra data sent with the notifications.

The [doc](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) mentions the `data` field, which is optional, and we've been using that to send important push-related information to users.

I opened a PR (https://github.com/b8ne/react-native-pusher-push-notifications/pull/51) to do so in Android.

Is anyone willing to test it on iOS?

**Comment by Humni** [comment]
@GabrielePrestifilippo  LGTM - running some tests over the next week before releasing

**Comment by Humni** [comment]
Resolved by #55
