### ISSUE TITLE
Can not handle notification data when application in background or close in android.

### ISSUE THREAD

**Issue by TrushalRank** [b8ne/react-native-pusher-push-notifications#59]
When application is in background mode and get the push notification, but when user tap on notification there are not getting notification listener method call. So, i can't handle push notification data when application is in background and can not perform any action on notification tap. This error is facing only in android platform.

Note: On foreground mode listener method works.

**Comment by Ahmdrza** [comment]
@TrushalRank We are getting the same issue. Did you find any solution?

**Comment by pedromcunha** [comment]
@TrushalRank also experiencing the same issue, did you find a way to get around it?

**Comment by Humni** [comment]
We're currently testing this PR which should fix your issue. Please pull the branch yourself to confirm (if so, I'll create a new release) https://github.com/b8ne/react-native-pusher-push-notifications/pull/51

**Comment by Humni** [comment]
Resolved by #55
