### ISSUE TITLE
Pusher/Pusher.h not found

### ISSUE THREAD

**Issue by suprb** [b8ne/react-native-pusher-push-notifications#6]
Hey! Thanks for doing this. 

Unfortunately, I get the error message "Pusher/Pusher.h file not found" when building the app. Followed the instructions and everything.

Any ideas?

**Comment by suprb** [comment]
Reinstalled Pusher and it works now.

**Comment by realripley00** [comment]
I'm having this same issue. I've yarn removed pusher-js and react-native-pusher-push-notifications and then yarn added them again, but it's still giving me this Pusher/Pusher.h not found whenever I try to compile.  

Is yarn removing and re-adding what you meant by Reinstalled Pusher? Any other ideas what I might be doing wrong to get this error?
