### ISSUE TITLE
JavaBinder: FAILED BINDER TRANSACTION [Android]

### ISSUE THREAD

**Issue by TerrerSandman** [b8ne/react-native-pusher-push-notifications#60]
My app is all working fine until I implement this package. It's causing my app to crash when I send a notification from Pusher Debug Console. I checked using adb logcat and it show the errors below.

`09-10 10:41:04.844 19258 19527 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)
09-10 10:41:04.942  1070  1151 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1504)
09-10 10:41:04.975  1070  1160 E touchscreen: Open /sys/touchscreen/app_name failed
09-10 10:41:04.980  1464  4256 E _V_ActivityManagerDelegate: no forceStopPackageWithoutCancelNotification.
09-10 10:41:04.980  1576  1651 E ProxCoverNoticeService: monitor view is null, no need to update fullscreen
09-10 10:41:05.108  1070  1248 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=8461, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
09-10 10:41:05.287 11745 11812 E MAL-RDS :  (  rds_ru_3gpp_status_ind, 1969) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8 sim:1
09-10 10:41:05.569 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.570 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.570 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.572 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.572 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.572 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.574 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.574 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.575 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.576 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.576 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.577 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.577 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.577 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.582 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.582 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.582 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.583 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.584 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.584 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.585 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.587 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.587 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.588 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.588 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.589 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.589 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.589 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.594 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.594 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.597 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.598 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.598 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.599 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.599 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.600 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.600 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.605 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.605 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.607 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.608 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.608 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.611 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.611 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.613 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.613 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.614 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.632 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.636 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.636 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.639 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.639 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.639 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.640 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.640 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.640 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.641 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.653 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.657 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.657 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.658 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.659 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.663 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.663 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.665 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.665 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.665 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.666 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.666 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.666 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.666 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.669 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.669 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.669 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.670 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.670 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.671 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.671 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.672 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.674 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.676 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.677 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.677 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.688 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.688 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.691 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.691 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.693 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.693 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.693 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.698 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.698 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.699 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.699 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.699 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.699 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.700 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.700 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.704 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.704 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.705 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.705 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.705 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.705 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.705 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.706 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.707 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.714 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.714 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.714 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.715 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.715 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.717 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.717 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.717 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.718 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.720 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.721 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.721 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.723 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.723 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.724 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.724 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.724 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.727 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.731 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.731 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.731 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.733 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.733 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.735 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.735 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.735 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.736 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.736 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.737 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.737 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.737 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.738 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.738 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.738 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.748 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.748 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.748 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.749 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.749 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.749 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.750 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.750 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.750 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.751 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.751 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.751 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.752 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.752 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.752 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.752 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.753 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.753 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.753 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.753 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.756 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.756 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.757 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.758 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.758 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.759 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.759 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.761 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.761 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.762 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.762 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.764 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.764 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.764 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.766 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.766 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.767 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.767 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.768 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.768 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.769 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.771 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.774 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.775 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.775 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.776 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.776 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.777 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.777 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.779 21787 21812 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.779 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.779 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.781 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.781 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.781 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.782 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.783 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#beginTransaction
09-10 10:41:05.783 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.783 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.785 21787 21822 E CrashFixLancet: androidx.room.RoomDatabase#endTransaction
09-10 10:41:05.787 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.787 21787 21810 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction
09-10 10:41:05.789 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#query
09-10 10:41:05.789 21787 21808 E CrashFixLancet: androidx.room.RoomDatabase#assertNotSuspendingTransaction`

DEPENDENCIES
pusher-js: ^7.0.0
react-native: 0.59.10
react-native-firebase: ^5.6.0
react-native-pusher-push-notifications: git+http://git@github.com/ZeptInc/react-native-pusher-push-notifications#v.2.4.0-zept-master

**Comment by Humni** [comment]
@TerrerSandman did you find any solution to this?
