### ISSUE TITLE
How to get extra data from notification when any notification is clicked in notification tray? 

### ISSUE THREAD

**Issue by Ahmdrza** [b8ne/react-native-pusher-push-notifications#61]
I want to navigate to a specific screen on click but opening the app via notification doesn't return anything. It just opens the app.

**Comment by vlad-dewitt** [comment]
Any updates?

**Comment by Humni** [comment]
@vlad-dewitt on what platform are you having this issue on? There is an open PR which is currently being tested which fixes the notification data for Android https://github.com/b8ne/react-native-pusher-push-notifications/pull/51

**Comment by Humni** [comment]
Resolved by #55
