### ISSUE TITLE
Allow higher versions than RN 0.60

### ISSUE THREAD

**Issue by abury** [b8ne/react-native-pusher-push-notifications#67]
Currently can't install RNPPN due to the following dependency issue:

`
npm install react-native-pusher-push-notifications --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: <appname>@0.0.1
npm ERR! Found: react-native@0.64.0-rc.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0-rc.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.60.0" from react-native-pusher-push-notifications@2.5.1
npm ERR! node_modules/react-native-pusher-push-notifications
npm ERR!   react-native-pusher-push-notifications@"*" from the root project
`

Can we bump this up to allow higher versions of RN?

**Comment by Humni** [comment]
@abury can you open a PR for this? I'll get it reviewed and merged

**Comment by Humni** [comment]
Resolved by #82
