### ISSUE TITLE
RN Pusher push notifications.setUp key null

### ISSUE THREAD

**Issue by ghulamHaiderbuggy** [b8ne/react-native-pusher-push-notifications#73]
![Screenshot_20210521-165810](https://user-images.githubusercontent.com/71820782/119134092-25db1280-ba56-11eb-8f57-218902c1fa4b.png)

**Comment by Humni** [comment]
@ghulamHaiderbuggy when opening a ticket, you need to provide more information than just the error message. i.e. what is the code you're running which triggers it? Are you setting the app key correctly and is it valid? For now I'm closing this ticket until there is enough information to help assist you in fixing it

**Comment by ghulamHaiderbuggy** [comment]
how can i set the app key
