### ISSUE TITLE
On click notification when app is killed

### ISSUE THREAD

**Issue by vuthanhtrung0504** [b8ne/react-native-pusher-push-notifications#74]
Do we have any way to get the payload or extra data when user clicks on the notification to open the app when the app is killed?

**Comment by Humni** [comment]
See the readme for reference:  https://github.com/b8ne/react-native-pusher-push-notifications#data-handling-android

**Comment by vuthanhtrung0504** [comment]
That did not help at all. Your doc just reference handle on the native side, not js side, and also it is for android, how about ios?

**Comment by gabrielbezerra81** [comment]
I recommend using [react-native-notifications](https://github.com/wix/react-native-notifications) for Android and its working perfect. Making it work without that library needs a lot of hacks in my experience. For iOS I'm using [@react-native-community/push-notification-ios](https://github.com/react-native-push-notification-ios/push-notification-ios), still need to check if works nice with react-native-notifications.

**Comment by Humni** [comment]
@vuthanhtrung0504 we have this working from the readme in several applications - if you have a specific issue please provide details around how to replicate it and a code example would be very useful.
