### ISSUE TITLE
"Registered" event callback not being called

### ISSUE THREAD

**Issue by augustoabreu** [b8ne/react-native-pusher-push-notifications#8]
Hi! First of all i would like to thanks for the library! It is an amazing idea!

But, i'm facing some problems and i can't figure out how to solvem them:

1. My callback of .on('registered', callback) is not being called after registered event. Anyone with this problem?

2. When subscribing to an interest and sending it trough NodeJS script it does not appears on my app.

Thanks again!

**Comment by se1exin** [comment]
Hi @augustoabreu, does it work if you do this:

`PSNotifications.on('registered', () => {this.initChannels()})`

Rather than

`PSNotifications.on('registered', initChannels)`?

I've had some issues with callbacks before and wrapping the function in an inline function got it to work

**Comment by augustoabreu** [comment]
@se1exin It didn't work :(

I'm receiving this log:

Creating pusher with App Key: 5ce798cd59cc891f3532
setDeviceToken: <160b0a92 10cdc28e cb787fb2 c3d08600 e04d153e e4ae6dd8 19bf3e02 e859e8c8>
Sending 'registered' with no listeners registered.

**Comment by se1exin** [comment]
OK @augustoabreu  thanks for the feedback. I'll try to reproduce, what version of `react-native` and `react-native-pusher-push-notifications` are you using?

**Comment by b8ne** [comment]
@se1exin just had a quick look at this. given the events are running on independent threads i guess there's no guarantee that the event will be subscribed to before it is emitted, hence the 'no listeners registered' warning.
To avoid async programming may just need to wrap the emitter in a loop until the listener inits? The issue of events running on their own thread should be a benefit here as the loop shouldn't lead to any deadlocks.

**Comment by augustoabreu** [comment]
@se1exin @b8ne 

react-native-cli: 2.0.1
react-native: 0.43.3
node: 6.9.2
npm: 4.2.0
react-native-pusher-push-notifications: ^1.0.1

**Comment by ahmed-wagdi** [comment]
I'm having the same problem, any update on this?

**Comment by se1exin** [comment]
@b8ne that makes sense, thanks. Doing some overtime at the moment so will have an iOS RN project in my hands later tonight, I'll have a go working on threading then and report finds here.

**Comment by augustoabreu** [comment]
@se1exin @b8ne @ahmed-wagdi 

After updated my react-native to 0.46.4 the registered event started to work as it should. With #9 seems like the library it is not crashing anymore.

But beside that, after .subcribe() call my app don't receive any notification.

I've already tested with HTTP calls to Pusher's API (https://pusher.com/docs/push_notifications/reference/client_api) and it works.

**Comment by se1exin** [comment]
Hi @augustoabreu - Good to hear things are working better, just to be clear, are you or are you not receiving notifications when testing with Pusher's API. Also, are you testing actual Push Notifications, or general websocket channels/interests?

**Comment by b8ne** [comment]
Sorry @se1exin i dont have any decent projects to test this on atm.  A key point to test is a console log when a channel is subscribed to.  I know pusher doesnt trigger anything if there are no watchers so it would be best to ensure that the subscription is valid first.

**Comment by augustoabreu** [comment]
@se1exin 

I registered my iphone using HTTP calls to Pusher's API. Using pusher-js lib i received notification as expected. After that i tested with react-native-pusher-push-notifications but i didn't work.

It's a shame we don't have success/error callbacks after subscribe() :(
