### ISSUE TITLE
Allow newer versions of react native

### ISSUE THREAD

**Issue by feardarkness** [b8ne/react-native-pusher-push-notifications#83]
When I try to install react-native-pusher-push-notifications on a newer version of react-native an error is thrown because currently only 0.60 is allowed.

I've created a PR to fix this issue: https://github.com/b8ne/react-native-pusher-push-notifications/pull/82

**Comment by Humni** [comment]
Resolved by #82

**Comment by Humni** [comment]
@feardarkness thank you very much for the contribution for this! Sorry it took so long to get it merged

**Comment by feardarkness** [comment]
@Humni Happy to help
