### ISSUE TITLE
Successfuly subscribed to interest on Android, can't receive notifications

### ISSUE THREAD

**Issue by hypnocill** [b8ne/react-native-pusher-push-notifications#96]
I followed the setup guides here (and also in the pusher beams page). The android app is building successfully. Then I setInstanceId and subscribe, and I get 'Success' from the subscribe success callback.
Despite that, I don't see the device in Pusher and when I try to send a notification (no matter if app is background/foreground/killed state), no matter the interest, etc, notifications are not coming at all. Tried on emulator and on a physical device.

Any help would be highly appreciated. Thank you!

**Comment by Lakshyakatarmal** [comment]
@hypnocill  can you please share the steps for setup?
